import { useQuery } from '@tanstack/react-query';
import type { Metadata } from 'next';
import React from 'react';
import styled from 'styled-components';

import useCount from '@/store/useCount';

type FetchDataResponse = {
  data: string;
};

const StyledButton = styled.button`
  padding: 10px 15px;
  font-size: 16px;
  border: none;
  border-radius: 5px;
  color: white;
  background-color: #0070f3;
  cursor: pointer;
  transition: background-color 0.3s;

  &:hover {
    background-color: #0051bf;
  }
`;

function fetchData(): Promise<FetchDataResponse> {
  return Promise.resolve({ data: 'Hello from API' });
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout() {
  const { count, increase, decrease } = useCount();
  const { data, error, isLoading } = useQuery<
    FetchDataResponse,
    Error
  >(['fetchData'], fetchData);

  if (isLoading) return <p>Loading...</p>;

  if (error) return <p>Error: {error.message}</p>;

  return (
    <div>
      <p>Data from API: {data?.data}</p>
      <p>Count: {count}</p>
      <StyledButton type="button" onClick={increase}>
        Increase
      </StyledButton>
      <StyledButton type="button" onClick={decrease}>
        Decrease
      </StyledButton>
    </div>
  );
}
